"""
Django settings for myforum project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import ConfigParser

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.dirname(BASE_DIR)

#config = ConfigParser.RawConfigParser()
#config.read(os.path.join(ROOT_DIR, 'conf/config.ini'))

DEFAULT_FROM_EMAIL = 'xqflame@sina.com' 
EMAIL_HOST = 'smtp.sina.com' 
EMAIL_PORT = 465 
EMAIL_HOST_USER = 'xqflame@sina.com' 
EMAIL_HOST_PASSWORD = '123x123' 
EMAIL_USE_SSL = True 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i$luw5$$vzcx5hj-_z1bo(g!^gzr6yixfy@c-ur3!xrc4l9q#a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'block',
    'article',
    'usercenter',
    'comment',
    'message',
    'ueditor',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'myforum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myforum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'forum_No7',
        'USER': 'root',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

#USER_RES_URL_BASE = config.get("Storage", "USER_RES_URL_BASE")
#STORAGE_PATH = config.get("Storage", "STORAGE_PATH")
#MEDIA_ROOT = config.get("Storage", "MEDIA_ROOT")
USER_RES_URL_BASE = 'http://114.215.145.64/upload'
STORAGE_PATH = '/usr/share/userres/avatar/'
MEDIA_ROOT = '/usr/share/userres/article/'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
          "format": "%(levelname)s %(asctime)s %(module)s %(message)s"
        },
        "simple": {
          "format": "%(levelname)s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple"
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(ROOT_DIR, "log/error.log"),
            "formatter": "verbose"
        },
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(ROOT_DIR, "log/info.log"),
            "formatter": "verbose"
        }
    },
    "loggers": {
        "forum_No7": {
            "handlers": ["console", "error_file", "info_file"],
            "level": "DEBUG",
        }
    }
}
